export const guides = [
  // Austin Campus
  {
    name: "Charity Villegas",
    role: "LEAD GUIDE / LEARNING LAB",
    bio: "Education from Bowdoin College & NYU School of Education. Specialized in executive function skills & RQ development. Former Learning Interventionist in private schools and Rikers Island education programs.",
    image: "/assets/guides/guide-img-placeholder.png",
    location: "Austin",
  },
  {
    name: "Tanya Parker",
    role: "LEARNING LAB",
    bio: "Educator and international birth justice advocate. Extensive experience in alternative education, world-schooling across South Africa, Australia, Europe, and Latin America. Consultant for self-directed learning models.",
    image: "/assets/guides/guide-img-placeholder.png",
    location: "Austin",
  },
  {
    name: "Carrington Haas",
    role: "LEARNING LAB",
    bio: "Degree in Political Science & International Studies. Board Certified Autism Technician (BCAT) with experience in Waldorf, charter schools, and Teach for America. Passionate about neurodivergent education.",
    image: "/assets/guides/guide-img-placeholder.png",
    location: "Austin",
  },
  {
    name: "Gwen Hurst",
    role: "READING SPECIALIST, LL + LINC",
    bio: "40+ years in education as a teacher, reading specialist, music, and PE instructor. Private swim instructor and literacy expert dedicated to fostering a lifelong love of reading.",
    image: "/assets/guides/guide-img-placeholder.png",
    location: "Austin",
  },
  {
    name: "Malu Delgado",
    role: "LEARNING LAB",
    bio: "9+ years in education. Background in creative advertising at the Moody College of Communication. Dedicated mentor to Alpha students, inspiring limitless learning.",
    image: "/assets/guides/guide-img-placeholder.png",
    location: "Austin",
  },
  {
    name: "Faith Crenshaw",
    role: "LEAD GUIDE, LINC",
    bio: "Management degree from UT Austin. Former co-captain of the Texas Cheerleading team. Passionate about coaching and guiding students to embrace their limitless potential.",
    image: "/assets/guides/guide-img-placeholder.png",
    location: "Austin",
  },
  {
    name: "Vanessa Watson",
    role: "LINC",
    bio: "Bachelor's in Early Childhood & Elementary Education. Master's in TESOL. 6+ years of experience teaching kindergarten, third grade, and ESL. Dedicated to helping students achieve beyond what they think is possible.",
    image: "/assets/guides/guide-img-placeholder.png",
    location: "Austin",
  },
  {
    name: "Taylor Sweeney",
    role: "LEAD GUIDE, LEVEL 2",
    bio: "Graduate of Texas Christian University with additional studies in Social Work at the University of North Carolina at Chapel Hill. Extensive experience in student coaching, interdisciplinary learning, and guide training at Alpha.",
    image: "/assets/guides/guide-img-placeholder.png",
    location: "Austin",
  },
  {
    name: "Phil Perkins",
    role: "LEVEL 2",
    bio: "Finance background turned educator. Former corporate banker with a degree in Investment Management & Financial Analysis. Helped launch a learner-led PK-5 school, redefining early education.",
    image: "/assets/guides/guide-img-placeholder.png",
    location: "Austin",
  },
  {
    name: "Bryan Gordon",
    role: "LEVEL 2",
    bio: "M.S. in Psychology with 17+ years of experience in health and wellness coaching, mentored by Olympians and world record holders. Expert in neuroscience and physiological psychology.",
    image: "/assets/guides/guide-img-placeholder.png",
    location: "Austin",
  },
  {
    name: "Andres Standard",
    role: "LEVEL 2",
    bio: "B.S. in Cognitive Psychology, M.S. in Applied Industrial & Organizational Psychology, PMP® certified. Extensive experience in education, project management, and community mentorship programs.",
    image: "/assets/guides/guide-img-placeholder.png",
    location: "Austin",
  },
  // Brownsville Campus
  {
    name: "Tyisha Brooks",
    role: "PRE-K",
    bio: "Experienced educator (K-3) with expertise in growth mindset & creative problem-solving. Published children's book author.",
    image: "/assets/guides/guide-img-placeholder.png",
    location: "Brownsville",
  },
  {
    name: "Ruby Alvarez",
    role: "PRE-K",
    bio: "Background in early childhood education. Former educator at Starbase, working with toddlers and fostering early developmental learning.",
    image: "/assets/guides/guide-img-placeholder.png",
    location: "Brownsville",
  },
  {
    name: "Giana Hesterberg",
    role: "PRE-K",
    bio: "Nearly 20 years in education. Keynote speaker at the Texas Association of Future Educators Conference and Los Fresnos CISD Secondary Teacher of the Year. Graduate student in Clinical Mental Health Counseling.",
    image: "/assets/guides/guide-img-placeholder.png",
    location: "Brownsville",
  },
  {
    name: "Samantha Hilton",
    role: "LEARNING LAB",
    bio: "Former Environmental Science & English teacher. Developed innovative teaching strategies for diverse learners in Brownsville public schools.",
    image: "/assets/guides/guide-img-placeholder.png",
    location: "Brownsville",
  },
  {
    name: "Desiré Park",
    role: "LINC / READING SPECIALIST",
    bio: "M.S. in Reading Specialization. Former Science Course Leader for 140+ teachers. Extensive experience in education leadership and student enrichment.",
    image: "/assets/guides/guide-img-placeholder.png",
    location: "Brownsville",
  },
  {
    name: "Michael O'Connor",
    role: "LEVEL 1",
    bio: "Background in Economics & Business. Developed a real-world financial literacy and business curriculum that led students to create and run their own profitable businesses.",
    image: "/assets/guides/guide-img-placeholder.png",
    location: "Brownsville",
  },
  {
    name: "Mo Swain",
    role: "LEVEL 2/3",
    bio: "10+ years in education. Founder of Alpha's workshop team & program, specializing in hands-on, innovative learning experiences.",
    image: "/assets/guides/guide-img-placeholder.png",
    location: "Brownsville",
  },
  {
    name: "Gabbi Piazza",
    role: "LL + LINC + ALPHAQUEST",
    bio: "Degree in Early Childhood Education. Specialist in neurodiverse education with extensive experience in summer camp leadership and immersive learning techniques.",
    image: "/assets/guides/guide-img-placeholder.png",
    location: "Brownsville",
  },
]; 